module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
    // Add any other paths that contain your components
  ],
  theme: {
    extend: {
      colors: {
        minimalist: {
          background: "#FFFFFF",
          text: "#000000",
          primary: "#007BFF",
          secondary: "#6C757D",
          highlight: "#FFC107",
          link: "#0056B3",
          error: "#DC3545",
          success: "#28A745",
        },
        darkmode: {
          background: "#121212",
          text: "#E0E0E0",
          primary: "#BB86FC",
          secondary: "#03DAC6",
          highlight: "#FFB74D",
          link: "#8AB4F8",
          error: "#CF6679",
          success: "#66BB6A",
        },
        retro: {
          background: "#F5F5DC",
          text: "#4B5320",
          primary: "#FF4500",
          secondary: "#FFD700",
          highlight: "#8B0000",
          link: "#4682B4",
          error: "#800000",
          success: "#32CD32",
        },
        pastel: {
          background: "#FFF0F5",
          text: "#6A5ACD",
          primary: "#FFB6C1",
          secondary: "#FFDAB9",
          highlight: "#E6E6FA",
          link: "#B0E0E6",
          error: "#FF6961",
          success: "#77DD77",
        },
        nature: {
          background: "#F0FFF0",
          text: "#2E8B57",
          primary: "#556B2F",
          secondary: "#8FBC8F",
          highlight: "#FFD700",
          link: "#4682B4",
          error: "#B22222",
          success: "#32CD32",
        },
        professional: {
          background: "#F8F9FA",
          text: "#343A40",
          primary: "#007BFF",
          secondary: "#6C757D",
          highlight: "#FFC107",
          link: "#0056B3",
          error: "#DC3545",
          success: "#28A745",
        },
        tech: {
          background: "#1E1E1E",
          text: "#D4D4D4",
          primary: "#0E76A8",
          secondary: "#00AEEF",
          highlight: "#00FA9A",
          link: "#FF4500",
          error: "#FF0000",
          success: "#00FF00",
        },
        sunset: {
          background: "#FFFAF0",
          text: "#4B0082",
          primary: "#FF7F50",
          secondary: "#FFD700",
          highlight: "#FF69B4",
          link: "#8A2BE2",
          error: "#DC143C",
          success: "#32CD32",
        },
      },
    },
  },
  plugins: [require("@tailwindcss/typography")],
};
